### ISSUE TITLE
IOS v0.7.5-dev.3 Error (Xcode) : Undefined symbol: _swift_FORCE_LOAD$_swiftCompatibility56

### ISSUE THREAD

**Issue by a7mdragab** [rafaelsetragni/awesome_notifications#841]
Hello,

## **1 - Describe the bug**
When I tried to upgrade to awesome_notifications: ^0.7.5-dev.3 with awesome_notifications_fcm: ^0.7.5-dev.3, 
I got the build error saying ``Error (Xcode): Undefined symbol: _swift_FORCE_LOAD$_swiftCompatibility56`` when running on IOS while android is working perfect.

## **2 - Provide us as much information as possible**
When returned back to awesome_notifications: ^0.7.4+1, It worked with no build errors

## **3 - How To Reproduce the Error**

Create a project with awesome_notifications: ^0.7.5-dev.3

## **4 - Expected behavior**
Run smoothly

**Comment by a7mdragab** [comment]
Up

**Comment by zzorba** [comment]
Seeing the same issue, any suggestions?

**Comment by rafaelsetragni** [comment]
You need to update your XCode and cocoapods with some urgency. Your machine doesn't have Swift at least 5.6 version.

**Comment by Bogghi** [comment]
Hi, @rafaelsetragni I'm currently on the same issue and my swift version is 5.7.2. is this error thrown for some relation with swift version? I'm running xcode 15.1 and while running my flutter app on xcode it works just fine but when i try to run it from intellijs ( wich use the cli )  i run into this error looking at xcode stacktracke: 

`ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/matteo/src/apprm_nca/build/ios/Debug-iphoneos/awesome_notifications_fcm/Flutter.framework/Flutter
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityPacks'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility56'
ld: warning: Could not find or use auto-linked library 'swiftObservation'
ld: warning: Could not find or use auto-linked framework 'Symbols'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeServiceExtension.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmEventsReceiver.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmListener.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmService.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(Crypto.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(FcmBackgroundExecutor.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(FcmBackgroundService.o)`

**Comment by bashiransari** [comment]
@Bogghi any updates on this one, I have the same issue. Here is my swift version
```
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.0
```

**Comment by Bogghi** [comment]
Hi @bashiransari, the only solution I've found was to completely remove xcode ( I used clean my mac ) and reinstall from scratch from the app store.
I believe that apple screw something up in some update as usual.

**Comment by bashiransari** [comment]
@Bogghi I am building the project in Azure pipeline using macOS-latest image. os, it's not about xcode. Evey build uses a clean image this issue appeared after upgrading asweome_notifiation to 0.8.2 from 0.7.4+1 
I reverted back the dependency in pubspec and it's working fine now. will wait for a proper fix before upgrade again

**Comment by iemreyildirim** [comment]
Hi,
I am facing the same problem. I am using xcode 14.2 and siwft version 5.7.2.
My Awesome notification Fcm version is ^0.8.0. And here is the log:

`Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftCompatibility56", referenced from:
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeServiceExtension.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmEventsReceiver.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmListener.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(AwesomeFcmService.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(Crypto.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(FcmBackgroundExecutor.o)
      __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore in IosAwnFcmCore(FcmBackgroundService.o)
      ...
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibility56_$_IosAwnFcmCore)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Is there any solution?
